export const GET_ROOM_LIST = "GET_ROOM_LIST";
export const GET_ROOM_LIST_SUCCESS = "GET_ROOM_LIST_SUCCESS";
export const GET_ROOM_LIST_FAILED = "GET_ROOM_LIST_FAILED";
export const SET_DEFAULT_ROOM = "SET_DEFAULT_ROOM";
export const CREATE_ROOM = "CREATE_ROOM";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const CREATE_ROOM_FAILED = "CREATE_ROOM_FAILED";

