export const GET_CURR_ROOM_INFO = "GET_CURR_ROOM_INFO";
export const GET_CURR_ROOM_INFO_SUCCESS = "GET_CURR_ROOM_INFO_SUCCESS";
export const GET_CURR_ROOM_INFO_FAILED = "GET_CURR_ROOM_INFO_FAILED";

export const GET_CURR_ROOM_AREA = "GET_CURR_ROOM_AREA";
export const GET_CURR_ROOM_AREA_SUCCESS = "GET_CURR_ROOM_AREA_SUCCESS";
export const GET_CURR_ROOM_AREA_FAILED = "GET_CURR_ROOM_AREA_FAILED";

export const GET_CURR_ROOM_ACCESS = "GET_CURR_ROOM_ACCESS";
export const GET_CURR_ROOM_ACCESS_SUCCESS = "GET_CURR_ROOM_ACCESS_SUCCESS";
export const GET_CURR_ROOM_ACCESS_FAILED = "GET_CURR_ROOM_ACCESS_FAILED";

export const GET_CURR_ROOM_ACTIVATE = "GET_CURR_ROOM_ACTIVATE";
export const GET_CURR_ROOM_ACTIVATE_SUCCESS = "GET_CURR_ROOM_ACTIVATE_SUCCESS";
export const GET_CURR_ROOM_ACTIVATE_FAILED = "GET_CURR_ROOM_ACTIVATE_FAILED";

export const GET_CURR_ROOM_SENSOR_MAP = "GET_CURR_ROOM_SENSOR_MAP";
export const GET_CURR_ROOM_SENSOR_MAP_SUCCESS = "GET_CURR_ROOM_SENSOR_MAP_SUCCESS";
export const GET_CURR_ROOM_SENSOR_MAP_FAILED = "GET_CURR_ROOM_SENSOR_MAP_FAILED";

export const GET_CURR_ROOM_SENSOR_LIST = "GET_CURR_ROOM_SENSOR_LIST";
export const GET_CURR_ROOM_SENSOR_LIST_SUCCESS = "GET_CURR_ROOM_SENSOR_LIST_SUCCESS";
export const GET_CURR_ROOM_SENSOR_LIST_FAILED = "GET_CURR_ROOM_SENSOR_LIST_FAILED";


export const GET_STATIONS = "GET_STATIONS";
export const GET_STATIONS_SUCCESS = "GET_STATIONS_SUCCESS";
export const GET_STATIONS_FAILED = "GET_STATIONS_FAILED";

export const SET_DEFAULT_AREA = "SET_DEFAULT_AREA";
export const SET_DEFAULT_AREA_SUCCESS = "SET_DEFAULT_AREA_SUCCESS";
export const SET_DEFAULT_AREA_FAILED = "SET_DEFAULT_AREA_FAILED";

export const ADD_SENSOR = "ADD_SENSOR";
export const ADD_SENSOR_SUCCESS = "ADD_SENSOR_SUCCESS";
export const ADD_SENSOR_FAILED = "ADD_SENSOR_FAILED";

export const ADD_ACCESS = "ADD_ACCESS";
export const ADD_ACCESS_SUCCESS = "ADD_ACCESS_SUCCESS";
export const ADD_ACCESS_FAILED = "ADD_ACCESS_FAILED";

export const ADD_ACTIVATE = "ADD_ACTIVATE";
export const ADD_ACTIVATE_SUCCESS = "ADD_ACTIVATE_SUCCESS";
export const ADD_ACTIVATE_FAILED = "ADD_ACTIVATE_FAILED";

export const UPDATE_SENSOR = "UPDATE_SENSOR";
export const UPDATE_SENSOR_SUCCESS = "UPDATE_SENSOR_SUCCESS";
export const UPDATE_SENSOR_FAILED = "UPDATE_SENSOR_FAILED";

export const UPDATE_ACCESS = "UPDATE_ACCESS";
export const UPDATE_ACCESS_SUCCESS = "UPDATE_ACCESS_SUCCESS";
export const UPDATE_ACCESS_FAILED = "UPDATE_ACCESS_FAILED";

export const UPDATE_ACTIVATE = "UPDATE_ACTIVATE";
export const UPDATE_ACTIVATE_SUCCESS = "UPDATE_ACTIVATE_SUCCESS";
export const UPDATE_ACTIVATE_FAILED = "UPDATE_ACTIVATE_FAILED";

export const DELETE_SENSOR = "DELETE_SENSOR";
export const DELETE_SENSOR_SUCCESS = "DELETE_SENSOR_SUCCESS";
export const DELETE_SENSOR_FAILED = "DELETE_SENSOR_FAILED";

export const DELETE_ACCESS = "DELETE_ACCESS";
export const DELETE_ACCESS_SUCCESS = "DELETE_ACCESS_SUCCESS";
export const DELETE_ACCESS_FAILED = "DELETE_ACCESS_FAILED";

export const DELETE_ACTIVATE = "DELETE_ACTIVATE";
export const DELETE_ACTIVATE_SUCCESS = "DELETE_ACTIVATE_SUCCESS";
export const DELETE_ACTIVATE_FAILED = "DELETE_ACTIVATE_FAILED";

